language: C
sudo: required

git:
  depth: false

matrix:
  include:
    - os: osx
    - os: linux
      env: TARGET_ARCH=amd64 RID=ubuntu.16.04-x64   RELEASE=xenial  VERSION=16.04
    - os: linux
      env: TARGET_ARCH=arm64 RID=ubuntu.16.04-arm64 RELEASE=xenial  VERSION=16.04

install:
  - ./ci/$(TRAVIS_OS_NAME).sh
 
before_script:
  - lsusb

script:
  - schroot -c $RID -- VERSION=$VERSION; RID=$RID; echo Running on version $VERSION with rid $RID; ci/build.sh