language: csharp
mono: none
dotnet: 2.1.400
sudo: required 

git:
  depth: false

install:
  - ./ci/linux.sh
 
before_script:
  - lsusb

script:
  - cd src/
  - dotnet pack LibUsb.Common/LibUsb.Common.csproj -c Release
  - dotnet pack LibUsbDotNet/LibUsbDotNet.csproj -c Release
  - dotnet pack LibUsbDotNet.LibUsb/LibUsbDotNet.LibUsb.csproj -c Release
  - dotnet pack LibUsbDotNet.Windows/LibUsbDotNet.Windows.csproj -c Release
