<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <NoWarn>$(NoWarn);NU1507</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Core.Clang" Version="6.0.0-alpha1" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="16.5.0" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="1.0.0" />
    <PackageVersion Include="Native.LibClang.win-x64" Version="5.0.0-alpha1" />
    <PackageVersion Include="Nerdbank.GitVersioning" Version="3.4.244" />
    <PackageVersion Include="Nustache" Version="1.16.0.8" />
    <PackageVersion Include="xunit" Version="2.4.1" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="2.4.1" />
  </ItemGroup>
</Project>